core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *

app_name = 'core'
 
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('store/<slug>/', PartnerDetailView.as_view(), name='store'),
    path('contact_us/', Contact_Us, name='contact_us'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('partner_dashboard/', PartnerDashBoard, name='partner_dashboard'),
    path('partner_items/', PartnerItems, name='partner_items'),

    path('shop/', AllCategoryView, name='shop'),
    path('others/', OtherView, name='others'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path('admin_dashboard/', AdminDashBoard, name='admin_dashboard'),
    path('admin_profile/', UserAdminProfile, name='admin_profile'),
    path('pending_order/', PendingOrder, name='admin_pending_order'),
    path('all_categories/', AllCategory, name='all_categories'),
    
    path('items/', AllItems, name='all_items'),
    path('all_order/', AllOrder, name='all_order'),
    path('all_stores/', AllStores, name='all_stores'),
    path('all_admins/', AllAdmins, name='all_admins'),

    path('all_admins/edit/<str:pk>/', EditAdmin, name='edit_admin'),
    path('all_dispatchers/edit/<str:pk>/', EditDispatcher, name='edit_dispatcher'),

    path('all_stores/edit/<str:pk>/', EditPartner, name='edit_store'),
    path('all_customers/edit/<str:pk>/', EditCustomer, name='edit_customer'),
    path('all_dispatchers/', AllDispatchers, name='all_dispatchers'),
    path('all_customers/', AllCustomers, name='all_customers'),
    path('ongoing_order/', OnGoingOrder, name='ongoing_order'),
    path('delivered_order/', DeliveredOrder, name='delivered_order'),
    path('partner/<slug>/', PartnerView.as_view(), name='partner'),
    path('dispatch_dashboard/', DispatchDashBoard, name='dispatch_dashboard'),
    path('customer_dashboard/', CustomerDashBoard, name='customer_dashboard'),

    path('shipping_rate/', ShippingRate, name='shipping_rate'),
 
    path('accounts/upload/', UploadSignUp, name='upload'),
    path('accounts/address/', VerificationSignUp, name='address'),
    path('signup_success/', SuccessSignUp, name='signup_success'),
    path('change_password/', ChangePassword, name='change_password'),
    
    path('dispatch/<str:pk>/', UpdateOrder, name='update_order'),
    path('dispatch_order/<str:pk>/', Dispatch, name='dispatch_order'),
    path('dispatcher_pending_order/', DisPendingOrder, name='dispatcher_pending_order'),
    path('dispatcher_ongoing_order/', DisOnGoingOrder, name='dispatcher_ongoing_order'),
    path('dispatcher_delivered_order/', DisDeliveredOrder, name='dispatcher_delivered_order'),
    path('dispatcher_account_settings/', DispatcherAccountSettings, name='dispatcher_account_settings'),
    path('dispatcher_all_order/', DisAllOrder, name='dispatcher_all_order'),

    path('distance_calculator/', DistanceCalculator, name='distance_calculator'),



    path('partner_profile/', UserPartnerProfile, name='partner_profile'),
    path('partner_pending_order/', PartnerPendingOrder, name='partner_pending_order'),
    path('partner_ongoing_order/', PartnerOnGoingOrder, name='partner_ongoing_order'),
    path('partner_delivered_order/', PartnerDeliveredOrder, name='partner_delivered_order'),

    path('', views.adminsearch, name='adminsearch'),

    ###################################CUSTOMER#########################################
    path('customer_pending_order/', CustPendingOrder, name='customer_pending_order'),
    path('customer/order_history/', CustomerOrderHistory, name='customer_order_history'),
    path('customer/order_information/<str:pk>/', CustomerOrderInfo, name='customer_order_information'),
    path('customer_ongoing_order/', CustOngoingOrder, name='customer_ongoing_order'),
    path('customer_delivered_order/', CustDeliveredOrder, name='customer_delivered_order'),
    path('my_profile/', UserCustomerProfile, name='customer_profile'),
    path('customer/my_account/', MyAccountCustomer, name='customer_my_account'),
    path('customer/edit_information/', EditInfoCustomer, name='customer_edit_information'),
    path('customer/edit_address/', EditAddressCustomer, name='customer_edit_address'),
    ###################################CUSTOMER#########################################

    ###################################RIDER#########################################
    path('all_riders/', AllRiders, name='all_riders'),
    path('all_riders/edit/<str:pk>/', EditRider, name='edit_rider'),
    path('rider_dashboard/', RiderDashBoard, name='rider_dashboard'),
    path('rider_order_status/<str:pk>/', RiderOrderStatus, name='rider_order_status'),
    path('rider_status/', RiderStatus, name='rider_status'),
    path('update_item/<str:pk>', UpdateItem, name='update_item'),
    path('rider_account_settings/', RiderAccountSettings, name='rider_account_settings'),
    path('rider_pending_order/', RidePendingOrder, name='rider_pending_order'),
    path('rider_ongoing_order/', RideOngoingOrder, name='rider_ongoing_order'),
    path('rider_delivered_order/', RideDeliveredOrder, name='rider_delivered_order'),
    
    ###################################RIDER#########################################

    ###################################PARTNERSTORE#########################################

    path('partner_all_order/', PartnerAllOrder, name='partner_all_order'),
    

    ###################################PARTNERSTORE#########################################
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/partner/all_order.html
{% extends "partner/partner.html" %} 
{% load static %}
{% block content %}

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">							
	      <div class="row">
					<div class="col-12">
						<div class="card card-default">
							<div class="card-header card-header-border-bottom d-flex justify-content-between">
								<h2>All Orders</h2>
							</div>

							<div class="card-body">
                <div class="hoverable-data-table">
									<table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
										<thead>
											<tr>
                        <th>Item</th>
                        <th>Customer</th>
                        <th>Rider</th>
                        <th>Charge</th>
                        <th>Total</th>
                        <th>Date</th>
											</tr>
										</thead>

                    <tbody>
                      {% for all_orders in all %}
                        <tr>    
                          <td style="display: block;">
                            {% for items in all_orders.items.all %}
                              {{items.quantity}}pc. ({{items.item.title}} {{items.item.price}}) in {{items.partnerstore.store}}<br>
                            {% endfor %}
                          </td>

                          <td>{{all_orders.user.customer.first_name}} {{all_orders.user.customer.middle_name}} {{all_orders.user.customer.last_name}} {{all_orders.user.customer.suffix}}<br>
                            {{all_orders.user.customer.contact}}
                          </td>

                          <td>{{all_orders.rider.first_name}} {{all_orders.rider.middle_name}} {{all_orders.rider.last_name}} {{all_orders.rider.suffix}}<br>
                            {{all_orders.rider.contact}}
                          </td>
                          <td>Service charge: {{all_orders.service_charge}}<br>
                            Other: {{all_orders.surcharge}}
                          </td>
                          <td>{{all_orders.total}}</td>

                          <td>{{all_orders.date_ordered}}</td>
                      
                        </tr>
                      {% endfor %}
                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
        </div>
      </div>
    </div>

    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
  
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });

  var d = new Date();
    var year = d.getFullYear();
    document.getElementById("copy-year").innerHTML = year;
</script>
{% endblock extra_scripts %}

templates/partner/delivered_order.html
{% extends "partner/partner.html" %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">							
	      <div class="row">
					<div class="col-12">
						<div class="card card-default">
							<div class="card-header card-header-border-bottom d-flex justify-content-between">
								<h2>Delivered Orders</h2>
							</div>

							<div class="card-body">
                <div class="hoverable-data-table">
									<table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
										<thead>
											<tr>
                        <th>Item</th>
                        <th>Customer</th>
                        <th>Rider</th>
                        <th>Charge</th>
                        <th>Total</th>
                        <th>Date</th>
											</tr>
										</thead>

                    <tbody>
                      {% for delivered in dlv %}
                        <tr>    
                          <td style="display: block;">
                            {% for items in delivered.items.all %}
                              {{items.quantity}}pc. ({{items.item.title}} {{items.item.price}}) in {{items.partnerstore.store}}<br>
                            {% endfor %}
                          </td>

                          <td>{{delivered.user.customer.first_name}} {{delivered.user.customer.middle_name}} {{delivered.user.customer.last_name}} {{delivered.user.customer.suffix}}<br>
                            {{delivered.user.customer.contact}}
                          </td>

                          <td>{{delivered.rider.first_name}} {{delivered.rider.middle_name}} {{delivered.rider.last_name}} {{delivered.rider.suffix}}<br>
                            {{delivered.rider.contact}}
                          </td>
                          <td>Service charge: {{delivered.service_charge}}<br>
                            Other: {{delivered.surcharge}}
                          </td>
                          <td>{{delivered.total}}</td>

                          <td>{{delivered.date_ordered}}</td>
                      
                        </tr>
                      {% endfor %}
                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
        </div>
      </div>
    </div>

    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
  
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });

  var d = new Date();
    var year = d.getFullYear();
    document.getElementById("copy-year").innerHTML = year;
</script>
{% endblock extra_scripts %}

templates/partner/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Partner Dashboard">
  
  
    <title>{{request.user.partnerstore.first_name}}`s Dashboard</title>
  
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />
  
    <!-- PLUGINS CSS STYLE -->
    <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/data-tables/jquery.datatables.min.css' %}" rel="stylesheet" />
    <!-- No Extra plugin used -->
    
    <link href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet" />

    
    <!-- SLEEK CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/sleek.css' %}" />
  
    <!-- FAVICON -->
    <link href="assets/img/favicon.png" rel="shortcut icon" />
  
    <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
</head>

templates/partner/partner.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

    {% include "partner/head.html" %}
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}


    <body class="header-fixed sidebar-fixed sidebar-dark header-light" id="body">
        
        {% include "partner/body.html" %}

        <div class="mt-2">
            {% if messages %} {% for message in messages %}
            <div
              class="alert alert-{{ message.tags }} alert-dismissible fade show"
              role="alert"
            >
              {{ message }}
      
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
        <head>
            <!-- jquery -->
          
      
          <!-- cropper -->
      
        </head>
        {% endfor %} 
        {% endif %} 

        {% block content %} 
        {% endblock content %}

        {% block extra_body %} 
        {% endblock %} 

        {% block extra_scripts %}
        {% endblock extra_scripts %}
     
    </body>

</html>

templates/partner/partner_detail.html
{% extends 'base.html' %}

{% load static %} 

{% block content %}
  
	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'core:category' store.category.slug %}" class="s-text16">
			{{ store.category }}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{ store_title }}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">
						<div class="item-slick3" data-thumb="{{ store_profile_pic.url }}">
							<div class="wrap-pic-w">
								<img src="{{ store_profile_pic.url }}" alt="{{ store_title }}">
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text17 p-b-13">
					{{ store_title }}
				</h4>
				<span class="s-text7">
					Contact Number: {{ store.contact }}
				</span>
				<br>
				<span class="s-text7">
					Address: {{ store.address }}
				</span>
				<br>
				<span class="s-text7">
					E-mail: {{ store.email }}
				</span>

				<div class="p-t-33 p-b-60">
					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							
						</div>
					</div>
				</div>
				<br>
			
				<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Description
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							{{ store_description_short }}
						</p>
						<p class="s-text8">
							{{ store.description_long }}
						</p>
					</div>
				</div>	
			</div>
		</div>
	</div>


	<!-- Related Products -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						
						<h4 class="m-text14 p-b-7">
							Products
						</h4>
					
						<div class="wra-filter-bar">
							<div id="filter-bar"></div>
						</div>
			
					</div>

					<div class="search-product pos-relative bo4 of-hidden">
						<input class="s-text7 size6 p-l-23 p-r-50" type="text" name="search-product" placeholder="Search Products...">

						<button class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
							<i class="fs-12 fa fa-search" aria-hidden="true"></i>
						</button>
					</div>
				</div>
			</div>

			<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
										
				<!-- Product -->
				<div class="row">
					{% for item in object_list %}
						
					<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">

							<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
								<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 360px;">

								<div class="block2-overlay trans-0-4">
									<div class="block2-btn-addcart w-size1 trans-0-4{{item.get_label_display}}">
										<a href="{{item.get_absolute_url}}">

											<!-- Button -->
										<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Add to Cart
										</button>
									</div>
								</div>
							
								<div class="block2-txt p-t-20">
									<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5">
										{{item.title}}
									</a>

									<span class="block2-price m-text6 p-r-5">
										₱{{item.price}}
									</span>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>		
			<!-- ---- row end ------- -->

			<br>

			<!-- Pagination -->
			{% if is_paginated %}
			<div class="pagination flex-m flex-w p-t-26">
				{% if page_obj.has_previous %}
				<a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
					<span class="sr-only">Previous</span>
				</a>
				{% endif %}
				<a href="?page={{ page_obj.number }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{page_obj.number}}</a>
					
					
				{% if page_obj.has_next %}
				<a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
					<span aria-hidden="true">&raquo;</span>
					<span class="sr-only">Next</span>
				</a>
				{% endif %}
			</div>
			{% endif %}
		</div>
	</section>
	
	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>

	{% endblock content %}

templates/partner/partner_items.html
{% extends "partner/partner.html" %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style>
  .image {
      max-width: 100px;
      max-height: 100px;
      margin: 0 auto;
    }
</style>

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">
        <div class="row">
          <div class="col-12">
            <div class="card card-default">
              <div class="card-body">
                <ul class="nav nav-tabs px-3 px-xl-5 nav-style-border" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="timeline-tab" data-toggle="tab" href="#timeline" role="tab" aria-controls="timeline" aria-selected="false">Items</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="att-tab" data-toggle="tab" href="#att" role="tab" aria-controls="att" aria-selected="false">Add Item</a>
                  </li>
                </ul>

              <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="timeline" role="tabpanel" aria-labelledby="timeline-tab">
                  <div class="mt-5 profile-timeline-media">
                <div class="hoverable-data-table">
                  <table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Image</th>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Stock</th>
                        <th>Description Short</th>
                        <th>Description Long</th>
                        <th>Active</th>
                        <th></th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      {% for itms in item %}
                        <tr>
                          <td>{{itms.id}}</td>
                          <td style="padding: 0; width: 1px;"><img class="image" src="{{itms.image.url}}"></td>
                          <td>{{itms.category}}</td>
                          <td>{{itms.name}}</td>
                          <td>{{itms.price}}</td>
                          <td>{{itms.stock_no}}</td>
                          <td>{{itms.description_short}}</td>
                          <td>{{itms.description_long}}</td>
                          <td>{{itms.is_active}}</td>
                          <td class="text-right">
                            <div class="dropdown show d-inline-block widget-dropdown">
                              <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdown-recent-order2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static"></a>
                              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-recent-order2">
                                <li class="dropdown-item">
                                  <a href="{% url 'core:update_item' itms.id %}">Update</a>
                                </li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="att" role="tabpanel" aria-labelledby="att-tab">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <br>
                {{form.category|as_crispy_field}}
                {{form.name|as_crispy_field}}
                {{form.price|as_crispy_field}}
                {{form.stock_no|as_crispy_field}}
                {{form.description_short|as_crispy_field}}
                {{form.description_long|as_crispy_field}}
                {{form.image|as_crispy_field}}
                {{form.is_active|as_crispy_field}}
                
                <hr>
                <button type="submit" name="att" class="btn btn-primary">Add &raquo;</button>
              </form>
            </div>
              </div>
              </div>
              </div>
              </div>
        </div>
      </div>
    </div>
    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });

  jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });
</script>
{% endblock extra_scripts %}


<!--################################################################################


  <style>
    #customers {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      border-bottom: 1px solid #ddd;
      width: 100%;
    }
    #customers td {
      border: 1px solid #ddd;
      text-align: center;
    }

    #customers th {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: center;
      background-color: #4cb4c7;
      color: white;
      padding-top: 12px;
      padding-bottom: 12px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}
    #customers tr:hover {background-color: #ddd;}

    body
    {background-color: #ebeff5;}
    #total-orders{background-color: #4cb4c7;}
    #orders-delivered{background-color: #7abecc;}
    #orders-pending{background-color: #7CD1C0;}

    .image {
      max-width: 100px;
      max-height: 100px;
      margin: 0 auto;
    }
  </style>

  <div class="wrap_menu">
    <nav class="menu">
      <ul class="main_menu">
        <li><a href="/partner_dashboard/"><strong>Dashboard</strong></a></li>  
        <li><a href="/partner_items/"><strong>Items</strong></a></li>
        <li><a href="/post_item/"><strong>Add Item</strong></a></li> 
        <li><a href="#"><strong></strong></a></li>                                
      </ul>
    </nav>
  </div>

  <hr>     
    <div class="card card-body">
        <h3>Items</h3>
        <table id="customers">
            <tr>
              <th>Image</th>
              <th>Item</th>
              <th>Price</th>         
              <th>Category</th>
              <th>Stock</th>
              <th>Attribute</th>
              <th>Description</th>
              <th>Description Long</th>
              <th>Active</th>
              <th>Update</th>
            </tr>

            {% for item in item %}   
                <tr>  
                    <td style="padding: 0; width: 1px;"><img class="image" src="{{item.image.url}}"></td>
                    <td>{{item.title}}</td>
                    <td>₱ {{item.price}}0</td>
                    <td>{{item.category}}</td>
                    <td>{{item.stock_no}}</td>
                    {% for attrs in item.attr.all %}
                    <td style="display: block;">{{attrs}}</td>
                    {% endfor %}
                    <td>{{item.description_short}}</td>
                    <td>{{item.description_long}}</td>
                    <td>{{item.is_active}}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'core:update_item' item.id %}">Update &raquo;</a></td>
                </tr>
                {% endfor %}
        </table>
    </div>

################################################################################-->