core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *

app_name = 'core'
 
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('store/<slug>/', PartnerDetailView.as_view(), name='store'),
    path('contact_us/', Contact_Us, name='contact_us'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('partner_dashboard/', PartnerDashBoard, name='partner_dashboard'),
    path('partner_items/', PartnerItems, name='partner_items'),

    path('shop/', AllCategoryView, name='shop'),
    path('others/', OtherView, name='others'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path('admin_dashboard/', AdminDashBoard, name='admin_dashboard'),
    path('admin_profile/', UserAdminProfile, name='admin_profile'),
    path('pending_order/', PendingOrder, name='admin_pending_order'),
    path('all_categories/', AllCategory, name='all_categories'),
    
    path('items/', AllItems, name='all_items'),
    path('all_order/', AllOrder, name='all_order'),
    path('all_stores/', AllStores, name='all_stores'),
    path('all_admins/', AllAdmins, name='all_admins'),

    path('all_admins/edit/<str:pk>/', EditAdmin, name='edit_admin'),
    path('all_dispatchers/edit/<str:pk>/', EditDispatcher, name='edit_dispatcher'),

    path('all_stores/edit/<str:pk>/', EditPartner, name='edit_store'),
    path('all_customers/edit/<str:pk>/', EditCustomer, name='edit_customer'),
    path('all_dispatchers/', AllDispatchers, name='all_dispatchers'),
    path('all_customers/', AllCustomers, name='all_customers'),
    path('ongoing_order/', OnGoingOrder, name='ongoing_order'),
    path('delivered_order/', DeliveredOrder, name='delivered_order'),
    path('partner/<slug>/', PartnerView.as_view(), name='partner'),
    path('dispatch_dashboard/', DispatchDashBoard, name='dispatch_dashboard'),
    path('customer_dashboard/', CustomerDashBoard, name='customer_dashboard'),

    path('shipping_rate/', ShippingRate, name='shipping_rate'),
 
    path('accounts/upload/', UploadSignUp, name='upload'),
    path('accounts/address/', VerificationSignUp, name='address'),
    path('signup_success/', SuccessSignUp, name='signup_success'),
    path('change_password/', ChangePassword, name='change_password'),
    
    path('dispatch/<str:pk>/', UpdateOrder, name='update_order'),
    path('dispatch_order/<str:pk>/', Dispatch, name='dispatch_order'),
    path('dispatcher_pending_order/', DisPendingOrder, name='dispatcher_pending_order'),
    path('dispatcher_ongoing_order/', DisOnGoingOrder, name='dispatcher_ongoing_order'),
    path('dispatcher_delivered_order/', DisDeliveredOrder, name='dispatcher_delivered_order'),
    path('dispatcher_account_settings/', DispatcherAccountSettings, name='dispatcher_account_settings'),
    path('dispatcher_all_order/', DisAllOrder, name='dispatcher_all_order'),

    path('distance_calculator/', DistanceCalculator, name='distance_calculator'),



    path('partner_profile/', UserPartnerProfile, name='partner_profile'),
    path('partner_pending_order/', PartnerPendingOrder, name='partner_pending_order'),
    path('partner_ongoing_order/', PartnerOnGoingOrder, name='partner_ongoing_order'),
    path('partner_delivered_order/', PartnerDeliveredOrder, name='partner_delivered_order'),

    path('', views.adminsearch, name='adminsearch'),

    ###################################CUSTOMER#########################################
    path('customer_pending_order/', CustPendingOrder, name='customer_pending_order'),
    path('customer/order_history/', CustomerOrderHistory, name='customer_order_history'),
    path('customer/order_information/<str:pk>/', CustomerOrderInfo, name='customer_order_information'),
    path('customer_ongoing_order/', CustOngoingOrder, name='customer_ongoing_order'),
    path('customer_delivered_order/', CustDeliveredOrder, name='customer_delivered_order'),
    path('my_profile/', UserCustomerProfile, name='customer_profile'),
    path('customer/my_account/', MyAccountCustomer, name='customer_my_account'),
    path('customer/edit_information/', EditInfoCustomer, name='customer_edit_information'),
    path('customer/edit_address/', EditAddressCustomer, name='customer_edit_address'),
    ###################################CUSTOMER#########################################

    ###################################RIDER#########################################
    path('all_riders/', AllRiders, name='all_riders'),
    path('all_riders/edit/<str:pk>/', EditRider, name='edit_rider'),
    path('rider_dashboard/', RiderDashBoard, name='rider_dashboard'),
    path('rider_order_status/<str:pk>/', RiderOrderStatus, name='rider_order_status'),
    path('rider_status/', RiderStatus, name='rider_status'),
    path('update_item/<str:pk>', UpdateItem, name='update_item'),
    path('rider_account_settings/', RiderAccountSettings, name='rider_account_settings'),
    path('rider_pending_order/', RidePendingOrder, name='rider_pending_order'),
    path('rider_ongoing_order/', RideOngoingOrder, name='rider_ongoing_order'),
    path('rider_delivered_order/', RideDeliveredOrder, name='rider_delivered_order'),
    
    ###################################RIDER#########################################

    ###################################PARTNERSTORE#########################################

    path('partner_all_order/', PartnerAllOrder, name='partner_all_order'),
    

    ###################################PARTNERSTORE#########################################
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/customer/customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

    {% include "customer/head.html" %}
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}


    <body class="header-fixed sidebar-fixed sidebar-dark header-light" id="body">
        
        {% include "customer/body.html" %}

        <div class="mt-2">
            {% if messages %} {% for message in messages %}
            <div
              class="alert alert-{{ message.tags }} alert-dismissible fade show"
              role="alert"
            >
              {{ message }}
      
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
        <head>
            <!-- jquery -->
          
      
          <!-- cropper -->
      
        </head>
        {% endfor %} 
        {% endif %} 

        {% block content %} 
        {% endblock content %}

        {% block extra_body %} 
        {% endblock %} 

        {% block extra_scripts %}
        {% endblock extra_scripts %}
     
    </body>

</html>

templates/customer/delivered_order.html
{% extends "customer/customer.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">							
	      <div class="row">
					<div class="col-12">
						<div class="card card-default">
							<div class="card-header card-header-border-bottom d-flex justify-content-between">
								<h2>Delivered Orders</h2>
							</div>

							<div class="card-body">
                <div class="hoverable-data-table">
									<table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
										<thead>
											<tr>
                        <th>Customer</th>
                        <th>Sugo</th>
                        <th>Shipping Address</th>
                        <th>Rider</th>
                        <th>Charges</th>
                        <th>Total charge</th>
                        <th>Pay via</th>
                        <th>Date</th>
                        <th style="text-align: right;">Dispatch</th>
											</tr>
										</thead>

                    <tbody>
                      {% for delivered in dlv %}
                        <tr>    
                          <td>{{delivered.user.customer.first_name}} {{delivered.user.customer.middle_name}} {{delivered.user.customer.last_name}} {{delivered.user.customer.suffix}}<br>
                            {{delivered.user.customer.contact}}
                          </td>

                          {% if delivered.other %}
                            <td>{{delivered.other.note}}</td>
                          {% else %}
                            <td style="display: block;">
                              {% for items in delivered.items.all %}
                                {{items.quantity}}pc. ({{items.item.title}} {{items.item.price}}) in {{items.partnerstore.store}}<br>
                              {% endfor %}
                            </td>
                          {% endif %}
                                
                          <td>{{delivered.shipping_address.house_purok_address}} {{delivered.shipping_address.barangay}}<br>
                            {{delivered.shipping_address.municipality}} {{delivered.shipping_address.province}}<br>
                          </td>   
                          <td>{{delivered.rider.first_name}} {{delivered.rider.middle_name}} {{delivered.rider.last_name}} {{delivered.rider.suffix}}<br>
                            {{delivered.rider.contact}}
                          </td>
                          <td>Service charge: {{delivered.service_charge}}<br>
                            Other: {{delivered.surcharge}}
                          </td>
                          <td>{{delivered.total}}</td>
                          <td>{{delivered.payment.payment_choice}}</td>
                          <td>{{delivered.date_ordered}}</td>
                          <td><a class="btn btn-primary float-right ml-2 far" style="padding-top: 2px; padding-bottom: 2px; padding-right: 2px; padding-left: 2px;" href="{% url 'core:update_order' delivered.id %}">Dispatch</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
        </div>
      </div>
    </div>

    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
  
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });

  var d = new Date();
    var year = d.getFullYear();
    document.getElementById("copy-year").innerHTML = year;
</script>
{% endblock extra_scripts %}

templates/customer/edit_info.html
{% extends 'base1.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<body class="account-edit">
    <div class="loader"></div>
    <div id="account-edit" class="container">
        <ul class="breadcrumb">
            <li><a href="/">home</a></li>
            <li><a href="/customer/my_account/">My Account</a></li>
            <li><a href="/customer/edit_information/">Edit Information</a></li>
        </ul>
        <div class="row">
            <aside id="column-left" class="col-sm-3 hidden-xs">
                <div class="account-content">
                    <div class="box-content">
                        <div class="list-group">
                            <h3 class="toggled">Account</h3>
                            <ul class="list-unstyled">
                                <li><a href="/customer/my_account/" class="list-group-item">My Account</a></li>
                                <li><a href="/customer/edit_information/" class="list-group-item">Edit Account</a></li>
                                <li> <a href="{% url 'core:change_password' %}" class="list-group-item">Edit password</a></li>
                                <li><a href="/customer/edit_address/" class="list-group-item">Edit Address</a></li>
                                <li><a href="/customer/order_history/" class="list-group-item">Order History</a></li>
                                <li><a href="https://opencart.mahardhi.com/MT03/food/index.php?route=account/logout" class="list-group-item">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="sidebar">
                    <div class="box-content">
                        <h3 class="box-content toggled">Information</h3>
                        <ul class="list-unstyled">
                            <li><a
                                    href="https://opencart.mahardhi.com/MT03/food/index.php?route=information/information&amp;information_id=4">About
                                    Us</a></li>
                            <li><a
                                    href="https://opencart.mahardhi.com/MT03/food/index.php?route=information/information&amp;information_id=3">Privacy
                                    Policy</a></li>
                            <li><a
                                    href="https://opencart.mahardhi.com/MT03/food/index.php?route=information/information&amp;information_id=5">Terms
                                    &amp; Conditions</a></li>
                            <li><a href="https://opencart.mahardhi.com/MT03/food/index.php?route=information/contact">Contact
                                    Us</a></li>
                            <li><a href="https://opencart.mahardhi.com/MT03/food/index.php?route=information/sitemap">Site
                                    Map</a></li>
                        </ul>
                    </div>
                </div>

            </aside>

            <div id="content" class="col-sm-9">
                <legend>Your Personal Details</legend>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.profile_pic|as_crispy_field}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <h4>Current picture</h4>
                            <div class="form-group">
                                {% if request.user.customer.profile_pic %}
                                <img class="card-img mx-auto rounded-circle" width="20%" height="20%"
                                    src="{{request.user.customer.profile_pic.url}}" alt="User Image">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.first_name|as_crispy_field}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.middle_name|as_crispy_field}}
                            </div>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.last_name|as_crispy_field}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.suffix|as_crispy_field}}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.contact|as_crispy_field}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{form1.gender|as_crispy_field}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        {{form1.email|as_crispy_field}}
                    </div>
                    <hr>
                    <div class="text-right">
                        <a href="{% url 'core:change_password' %}">Change Password</a>
                        <div class="d-flex justify-content-end mt-5">
                            <button type="submit" name="btnSetting" class="btn btn-primary">Update Profile</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% endblock content %}

templates/customer/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Customer Dashboard">
  
  
    <title>Customer Dashboard</title>
  
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />
  
    <!-- PLUGINS CSS STYLE -->
    <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/data-tables/jquery.datatables.min.css' %}" rel="stylesheet" />
    <!-- No Extra plugin used -->
    
    <link href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet" />

    
    <!-- SLEEK CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/sleek.css' %}" />
  
    <!-- FAVICON -->
    <link href="assets/img/favicon.png" rel="shortcut icon" />
  
    <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
</head>

templates/customer/order_history copy.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}

<div class="loader"></div>
<div id="account-order" class="container">
    <ul class="breadcrumb">
        <li><a href="/">home</a></li>
        <li><a href="/customer/my_account/">My Account</a></li>
        <li><a href="/customer/order_history/">Order History</a></li>
    </ul>
    <div class="row">
        <aside id="column-left" class="col-sm-3 hidden-xs">
            <div class="account-content">
                <div class="box-content">
                    <div class="list-group">
                        <h3 class="toggled">Account</h3>
                        <ul class="list-unstyled">
                            <li><a href="/customer/my_account/" class="list-group-item">My Account</a></li>
                            <li><a href="/customer/edit_information/" class="list-group-item">Edit Account</a></li>
                            <li><a href="{% url 'core:change_password' %}" class="list-group-item">Password</a></li>
                            <li><a href="/customer/edit_address/" class="list-group-item">Edit Address</a></li>
                            <li><a href="/customer/order_history/" class="list-group-item">Order History</a></li>
                            <li><a href="/accounts/logout/" class="list-group-item">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="sidebar">
                <div class="box-content">
                    <h3 class="box-content toggled">Information</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">About
                                Us</a></li>
                        <li><a href="#">Privacy
                                Policy</a></li>
                        <li><a href="#">Terms
                                &amp; Conditions</a></li>
                        <li><a href="#">Contact
                                Us</a></li>
                        <li><a href="#">Site
                                Map</a></li>
                    </ul>
                </div>
            </div>

        </aside>

        <div id="content" class="col-sm-9">
            <h1>Order History</h1>


            <div class="hoverable-data-table">
                <table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
                    <thead>
                        <tr>
                            <th>Customer</th>
                            <th>Sugo/Product</th>
                            <th>Status</th>
                            <th>Total</th>
                            <th>Date Ordered</th>
                            <th style="text-align: right;">Cancel</th>
                            <th>View</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for a in orders %}
                        <tr>
                            <td>{{ a.user.customer.first_name }}
                                {% if a.user.customer.middle_name %}
                                {{ a.user.customer.middle_name }}
                                {% endif %}
                                {{ a.user.customer.last_name }}
                                {% if user.customer.suffix %}
                                {{ a.user.customer.suffix }}
                                {% endif %}
                            </td>
                            {% if a.other %}
                            <td>{{a.other.note}}</td>
                            {% else %}
                            <td style="display: block; margin-top: 3%;">
                                {% for b in a.items.all %}
                                {{b.item.name}}<br>
                                {% endfor %}
                            </td>
                            {% endif %}
                            <td>{{ a.status }}</td>
                            <td>{{ a.total }}</td>
                            <td>{{ a.date_ordered }}</td>
                            <td>
                                <a class="btn btn-primary float-right ml-2 far"
                                    style="padding-top: 2px; padding-bottom: 2px; padding-right: 2px; padding-left: 2px;"
                                    href="{% url 'core:update_order' a.id %}">Cancel
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'core:customer_order_information' a.id %}" data-toggle="tooltip"
                                    title="View" class="btn btn-info">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extra_scripts %}

<script>

    jQuery(document).ready(function () {
        jQuery('#hoverable-data-table').DataTable({
            "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
            "pageLength": 20,
            "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
        });
    });
</script>
{% endblock extra_scripts %}

templates/customer/order_history.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}

<div class="loader"></div>
<div id="account-order" class="container">
    <ul class="breadcrumb">
        <li><a href="/">home</a></li>
        <li><a href="/customer/my_account/">My Account</a></li>
        <li><a href="/customer/order_history/">Order History</a></li>
    </ul>
    <div class="row">
        <aside id="column-left" class="col-sm-3 hidden-xs">
            <div class="account-content">
                <div class="box-content">
                    <div class="list-group">
                        <h3 class="toggled">Account</h3>
                        <ul class="list-unstyled">
                            <li><a href="/customer/my_account/" class="list-group-item">My Account</a></li>
                            <li><a href="/customer/edit_information/" class="list-group-item">Edit Account</a></li>
                            <li><a href="{% url 'core:change_password' %}" class="list-group-item">Password</a></li>
                            <li><a href="/customer/edit_address/" class="list-group-item">Edit Address</a></li>
                            <li><a href="/customer/order_history/" class="list-group-item">Order History</a></li>
                            <li><a href="/accounts/logout/" class="list-group-item">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="sidebar">
                <div class="box-content">
                    <h3 class="box-content toggled">Information</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">About
                                Us</a></li>
                        <li><a href="#">Privacy
                                Policy</a></li>
                        <li><a href="#">Terms
                                &amp; Conditions</a></li>
                        <li><a href="#">Contact
                                Us</a></li>
                        <li><a href="#">Site
                                Map</a></li>
                    </ul>
                </div>
            </div>

        </aside>

        <div id="content" class="col-sm-9">
            <h1>Order History</h1>
            <link href="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.css' %}" rel="stylesheet" />
            <link href="{% static 'assets/plugins/data-tables/jquery.datatables.min.css' %}" rel="stylesheet" />
            <div class="card-body">
                <div class="hoverable-data-table">
                    <table id="hoverable-data-table" class="table table-hover" style="width:auto;">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                <th>Sugo/Product</th>
                                <th>Status</th>
                                <th>Total</th>
                                <th>Date Ordered</th>
                                <th style="text-align: right;">Cancel</th>
                                <th>View</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for a in orders %}
                            <tr>
                                <td>{{ a.user.customer.first_name }}
                                    {% if a.user.customer.middle_name %}
                                    {{ a.user.customer.middle_name }}
                                    {% endif %}
                                    {{ a.user.customer.last_name }}
                                    {% if user.customer.suffix %}
                                    {{ a.user.customer.suffix }}
                                    {% endif %}
                                </td>
                                {% if a.other %}
                                <td>{{a.other.note}}</td>
                                {% else %}
                                <td style="display: block; margin-top: 3%;">
                                    {% for b in a.items.all %}
                                    {{b.item.name}}<br>
                                    {% endfor %}
                                </td>
                                {% endif %}
                                <td>{{ a.status }}</td>
                                <td>{{ a.total }}</td>
                                <td>{{ a.date_ordered }}</td>
                                <td>
                                    <a class="btn btn-primary float-right ml-2 far"
                                        style="padding-top: 2px; padding-bottom: 2px; padding-right: 2px; padding-left: 2px;"
                                        href="{% url 'core:update_order' a.id %}">Cancel
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'core:customer_order_information' a.id %}" data-toggle="tooltip"
                                        title="View" class="btn btn-info">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    {% endblock content %}

    {% block extra_scripts %}

    <script>

        jQuery(document).ready(function () {
            jQuery('#hoverable-data-table').DataTable({
                "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
                "pageLength": 20,
                "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
            });
        });
    </script>
    {% endblock extra_scripts %}