core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *

app_name = 'core'
 
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('store/<slug>/', PartnerDetailView.as_view(), name='store'),
    path('contact_us/', Contact_Us, name='contact_us'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('partner_dashboard/', PartnerDashBoard, name='partner_dashboard'),
    path('partner_items/', PartnerItems, name='partner_items'),

    path('shop/', AllCategoryView, name='shop'),
    path('others/', OtherView, name='others'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path('admin_dashboard/', AdminDashBoard, name='admin_dashboard'),
    path('admin_profile/', UserAdminProfile, name='admin_profile'),
    path('pending_order/', PendingOrder, name='admin_pending_order'),
    path('all_categories/', AllCategory, name='all_categories'),
    
    path('items/', AllItems, name='all_items'),
    path('all_order/', AllOrder, name='all_order'),
    path('all_stores/', AllStores, name='all_stores'),
    path('all_admins/', AllAdmins, name='all_admins'),

    path('all_admins/edit/<str:pk>/', EditAdmin, name='edit_admin'),
    path('all_dispatchers/edit/<str:pk>/', EditDispatcher, name='edit_dispatcher'),

    path('all_stores/edit/<str:pk>/', EditPartner, name='edit_store'),
    path('all_customers/edit/<str:pk>/', EditCustomer, name='edit_customer'),
    path('all_dispatchers/', AllDispatchers, name='all_dispatchers'),
    path('all_customers/', AllCustomers, name='all_customers'),
    path('ongoing_order/', OnGoingOrder, name='ongoing_order'),
    path('delivered_order/', DeliveredOrder, name='delivered_order'),
    path('partner/<slug>/', PartnerView.as_view(), name='partner'),
    path('dispatch_dashboard/', DispatchDashBoard, name='dispatch_dashboard'),
    path('customer_dashboard/', CustomerDashBoard, name='customer_dashboard'),

    path('shipping_rate/', ShippingRate, name='shipping_rate'),
 
    path('accounts/upload/', UploadSignUp, name='upload'),
    path('accounts/address/', VerificationSignUp, name='address'),
    path('signup_success/', SuccessSignUp, name='signup_success'),
    path('change_password/', ChangePassword, name='change_password'),
    
    path('dispatch/<str:pk>/', UpdateOrder, name='update_order'),
    path('dispatch_order/<str:pk>/', Dispatch, name='dispatch_order'),
    path('dispatcher_pending_order/', DisPendingOrder, name='dispatcher_pending_order'),
    path('dispatcher_ongoing_order/', DisOnGoingOrder, name='dispatcher_ongoing_order'),
    path('dispatcher_delivered_order/', DisDeliveredOrder, name='dispatcher_delivered_order'),
    path('dispatcher_account_settings/', DispatcherAccountSettings, name='dispatcher_account_settings'),
    path('dispatcher_all_order/', DisAllOrder, name='dispatcher_all_order'),

    path('distance_calculator/', DistanceCalculator, name='distance_calculator'),



    path('partner_profile/', UserPartnerProfile, name='partner_profile'),
    path('partner_pending_order/', PartnerPendingOrder, name='partner_pending_order'),
    path('partner_ongoing_order/', PartnerOnGoingOrder, name='partner_ongoing_order'),
    path('partner_delivered_order/', PartnerDeliveredOrder, name='partner_delivered_order'),

    path('', views.adminsearch, name='adminsearch'),

    ###################################CUSTOMER#########################################
    path('customer_pending_order/', CustPendingOrder, name='customer_pending_order'),
    path('customer/order_history/', CustomerOrderHistory, name='customer_order_history'),
    path('customer/order_information/<str:pk>/', CustomerOrderInfo, name='customer_order_information'),
    path('customer_ongoing_order/', CustOngoingOrder, name='customer_ongoing_order'),
    path('customer_delivered_order/', CustDeliveredOrder, name='customer_delivered_order'),
    path('my_profile/', UserCustomerProfile, name='customer_profile'),
    path('customer/my_account/', MyAccountCustomer, name='customer_my_account'),
    path('customer/edit_information/', EditInfoCustomer, name='customer_edit_information'),
    path('customer/edit_address/', EditAddressCustomer, name='customer_edit_address'),
    ###################################CUSTOMER#########################################

    ###################################RIDER#########################################
    path('all_riders/', AllRiders, name='all_riders'),
    path('all_riders/edit/<str:pk>/', EditRider, name='edit_rider'),
    path('rider_dashboard/', RiderDashBoard, name='rider_dashboard'),
    path('rider_order_status/<str:pk>/', RiderOrderStatus, name='rider_order_status'),
    path('rider_status/', RiderStatus, name='rider_status'),
    path('update_item/<str:pk>', UpdateItem, name='update_item'),
    path('rider_account_settings/', RiderAccountSettings, name='rider_account_settings'),
    path('rider_pending_order/', RidePendingOrder, name='rider_pending_order'),
    path('rider_ongoing_order/', RideOngoingOrder, name='rider_ongoing_order'),
    path('rider_delivered_order/', RideDeliveredOrder, name='rider_delivered_order'),
    
    ###################################RIDER#########################################

    ###################################PARTNERSTORE#########################################

    path('partner_all_order/', PartnerAllOrder, name='partner_all_order'),
    

    ###################################PARTNERSTORE#########################################
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/rider/body.html
{% load static %}

<body>
    <script>
        NProgress.configure({ showSpinner: false });
        NProgress.start();
    </script>
  
    <!--====================================
            ——— LEFT SIDEBAR WITH FOOTER
            =====================================-->
    <aside class="left-sidebar bg-sidebar">
        <div id="sidebar" class="sidebar sidebar-with-footer">
            <!-- Aplication Brand -->
            <div class="app-brand">
                <a href="/customer_dashboard" title="Customer Dashboard">
                    <svg class="brand-icon" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" width="30" height="33" viewBox="0 0 30 33">
                        <g fill="none" fill-rule="evenodd">
                            <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                            <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z" />
                        </g>
                    </svg>
                    <span class="brand-name text-truncate">Dashboard</span>
                </a>
            </div>
            <!-- begin sidebar scrollbar -->
            <div class="sidebar-scrollbar">
    
                <!-- sidebar menu -->
                <ul class="nav sidebar-inner" id="sidebar-menu"> 
                    <li  class="has-sub" >
                        <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#dashboard" aria-expanded="false" aria-controls="dashboard">
                            <i class="mdi mdi-view-dashboard-outline"></i>
                            <span class="nav-text">Dashboard</span> 
                            <b class="caret"></b>
                        </a>
                        <ul  class="collapse"  id="dashboard" data-parent="#sidebar-menu">
                            <div class="sub-menu">
                                <li >
                                    <a class="sidenav-item-link" href="/">
                                        <span class="nav-text">Sulogoon Website</span>
                                    </a>
                                </li>
                            </div>
                        </ul>
                    </li>

                    <li class="has-sub" >
                        <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#app" aria-expanded="false" aria-controls="app">
                            <i class="mdi mdi-pencil-box-multiple"></i>
                            <span class="nav-text">Orders</span> 
                            <b class="caret"></b>
                        </a>

                        <ul class="collapse"  id="app" data-parent="#sidebar-menu">
                            <div class="sub-menu">
                                <li >
                                    <a class="sidenav-item-link" href="#">
                                        <span class="nav-text">All Orders</span>
                                        <span class="badge badge-success">{{total_orders}}</span>
                                    </a>
                                </li>
                                <li >
                                    <a class="sidenav-item-link" href="/rider_pending_order">
                                        <span class="nav-text">Pending</span>
                                        <span class="badge badge-success">{{pending}}</span>
                                    </a>
                                </li>
                                <li >
                                    <a class="sidenav-item-link" href="/rider_ongoing_order">
                                        <span class="nav-text">On Going</span>
                                        <span class="badge badge-success">{{ongoing}}</span>
                                    </a>
                                </li>
                                <li >
                                    <a class="sidenav-item-link" href="/rider_delivered_order">
                                        <span class="nav-text">Delivered</span>
                                        <span class="badge badge-success">{{delivered}}</span>
                                    </a>
                                </li>
                            </div>
                        </ul>
                    </li>
        </div>
    </aside>

    <!-- Header -->
    <header class="main-header " id="header">
        <nav class="navbar navbar-static-top navbar-expand-lg">
            <!-- Sidebar toggle button -->
            <button id="sidebar-toggler" class="sidebar-toggle">
                <span class="sr-only">Toggle navigation</span>
            </button>
            <!-- search form -->
            <div class="search-form d-none d-lg-inline-block">
                <h2>Dashboard</h2>
            </div>
            <div class="navbar-right ">
                <ul class="nav navbar-nav">
                    <li class="dropdown notifications-menu">
                        <button class="dropdown-toggle" data-toggle="dropdown">
                            <i class="mdi mdi-bell-outline"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">You have 5 notifications</li>
                            <li>
                                <a href="#">
                                    <i class="mdi mdi-account-plus"></i> New user registered
                                    <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 10 AM</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="mdi mdi-account-remove"></i> User deleted
                                    <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 07 AM</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="mdi mdi-chart-areaspline"></i> Sales report is ready
                                    <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 12 PM</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="mdi mdi-account-supervisor"></i> New client
                                    <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 10 AM</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="mdi mdi-server-network-off"></i> Server overloaded
                                    <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 05 AM</span>
                                </a>
                            </li>
                            <li class="dropdown-footer">
                                <a class="text-center" href="#"> View All </a>
                            </li>
                        </ul>
                    </li>
                    <li class="right-sidebar-in right-sidebar-2-menu">
                        <i class="mdi mdi-settings mdi-spin"></i>
                    </li>
                    <!-- User Account -->
                    <li class="dropdown user-menu">
                        <button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            {% if request.user.rider.profile_pic %}
                                <img src="{{request.user.rider.profile_pic.url}}" class="user-image" alt="User Image" />
                            {% endif %}
                            {% if request.user.rider.first_name %}
                                <span class="d-none d-lg-inline-block">{{request.user.rider.first_name}} {{request.user.rider.last_name}}</span>
                            {% endif %}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <!-- User image -->
                            <li class="dropdown-header">
                                {% if request.user.rider.profile_pic %}
                                    <img src="{{request.user.rider.profile_pic.url}}" class="img-circle" alt="User Image" />
                                {% endif %}
                                <div class="d-inline-block">
                                    {% if request.user.rider.first_name %}
                                        {{request.user.rider.first_name}} {{request.user.rider.last_name}} <small class="pt-1">{{request.user.rider.email}}</small>
                                    {% endif %}
                                </div>
                            </li>
                            <li>
                                <a href="{% url 'core:rider_account_settings' %}">
                                    <i class="mdi mdi-account"></i> My Profile
                                </a>
                            </li>
                           
                            <li class="right-sidebar-in">
                                <a href="javascript:0"> <i class="mdi mdi-settings"></i> Setting </a>
                            </li>
                            <li class="dropdown-footer">
                                <a href="/accounts/logout"> <i class="mdi mdi-logout"></i> Log Out </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="right-sidebar-2">
        <div class="right-sidebar-container-2">
          <div class="slim-scroll-right-sidebar-2">
    
          <div class="right-sidebar-2-header">
            <h2>Layout Settings</h2>
            <p>User Interface Settings</p>
            <div class="btn-close-right-sidebar-2">
              <i class="mdi mdi-window-close"></i>
            </div>
          </div>
    
          <div class="right-sidebar-2-body">
            <span class="right-sidebar-2-subtitle">Header Layout</span>
            <div class="no-col-space">
              <a href="javascript:void(0);" class="btn-right-sidebar-2 header-fixed-to btn-right-sidebar-2-active">Fixed</a>
              <a href="javascript:void(0);" class="btn-right-sidebar-2 header-static-to">Static</a>
            </div>
    
            <span class="right-sidebar-2-subtitle">Sidebar Layout</span>
            <div class="no-col-space">
              <select class="right-sidebar-2-select" id="sidebar-option-select">
                <option value="sidebar-fixed">Fixed Default</option>
                <option value="sidebar-fixed-minified">Fixed Minified</option>
                <option value="sidebar-fixed-offcanvas">Fixed Offcanvas</option>
                <option value="sidebar-static">Static Default</option>
                <option value="sidebar-static-minified">Static Minified</option>
                <option value="sidebar-static-offcanvas">Static Offcanvas</option>
              </select>
            </div>
    
            <span class="right-sidebar-2-subtitle">Header Background</span>
            <div class="no-col-space">
              <a href="javascript:void(0);" class="btn-right-sidebar-2 btn-right-sidebar-2-active header-light-to">Light</a>
              <a href="javascript:void(0);" class="btn-right-sidebar-2 header-dark-to">Dark</a>
            </div>
    
            <span class="right-sidebar-2-subtitle">Navigation Background</span>
            <div class="no-col-space">
              <a href="javascript:void(0);" class="btn-right-sidebar-2 btn-right-sidebar-2-active sidebar-dark-to">Dark</a>
              <a href="javascript:void(0);" class="btn-right-sidebar-2 sidebar-light-to">Light</a>
            </div>
    
            <span class="right-sidebar-2-subtitle">Direction</span>
            <div class="no-col-space">
              <a href="javascript:void(0);" class="btn-right-sidebar-2 btn-right-sidebar-2-active ltr-to">LTR</a>
              <a href="javascript:void(0);" class="btn-right-sidebar-2 rtl-to">RTL</a>
            </div>
    
            <div class="d-flex justify-content-center" style="padding-top: 30px">
              <div id="reset-options" style="width: auto; cursor: pointer" class="btn-right-sidebar-2 btn-reset">Reset
                Settings</div>
            </div>
    
          </div>
    
        </div>
      </div>
    
    </div>

    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugins/slimscrollbar/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jekyll-search.min.js' %}"></script>
    <script src="{% static 'assets/plugins/charts/Chart.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-world-mill.js' %}"></script>
    <script src="{% static 'assets/plugins/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'assets/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'assets/plugins/data-tables/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/js/sleek.bundle.js' %}"></script>
</body>

templates/rider/dashboard_rider.html
{% extends "rider/rider.html" %} 
{% load static %}

{% block content %}
<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">

      <footer class="footer mt-auto">
        <div class="copyright bg-white">
          <p>
            &copy; <span id="copy-year">2021</span> Copyright Sulogoon Dashboard
          </p>
        </div>
      </footer>
    </div>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  var d = new Date();
  var year = d.getFullYear();
  document.getElementById("copy-year").innerHTML = year;

</script>

{% endblock extra_scripts %}

templates/rider/delivered_order.html
{% extends "rider/rider.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">							
	      <div class="row">
					<div class="col-12">
						<div class="card card-default">
							<div class="card-header card-header-border-bottom d-flex justify-content-between">
								<h2>Delivered Orders</h2>
							</div>

							<div class="card-body">
                <div class="hoverable-data-table">
									<table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
										<thead>
											<tr>
                        <th>Customer</th>
                        <th>Sugo</th>
                        <th>Shipping Address</th>
                        <th>Charges</th>
                        <th>Total charge</th>
                        <th>Pay via</th>
                        <th>Date</th>
                        <th style="text-align: right;">Status</th>
											</tr>
										</thead>

                    <tbody>
                      {% for delivered in dlv %}
                        <tr>    
                          <td>{{delivered.user.customer.first_name}} {{delivered.user.customer.middle_name}} {{delivered.user.customer.last_name}} {{delivered.user.customer.suffix}}<br>
                            {{delivered.user.customer.contact}}
                          </td>

                          {% if delivered.other %}
                            <td>{{delivered.other.note}}</td>
                          {% else %}
                            <td style="display: block;">
                              {% for items in delivered.items.all %}
                                {{items.quantity}}pc. ({{items.item.title}} {{items.item.price}}) in {{items.partnerstore.store}}<br>
                              {% endfor %}
                            </td>
                          {% endif %}
                                
                          <td>{{delivered.shipping_address.house_purok_address}} {{delivered.shipping_address.barangay}}<br>
                            {{delivered.shipping_address.municipality}} {{delivered.shipping_address.province}}<br>
                          </td>   
                          <td>Service charge: {{delivered.service_charge}}<br>
                            Other: {{delivered.surcharge}}
                          </td>
                          <td>{{delivered.total}}</td>
                          <td>{{delivered.payment.payment_choice}}</td>
                          <td>{{delivered.date_ordered}}</td>
                          <td class="text-right">
                            <div class="dropdown show d-inline-block widget-dropdown">
                              <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdown-recent-order2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static"></a>
                              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-recent-order2">
                                <li class="dropdown-item">
                                  <a href="{% url 'core:rider_order_status' delivered.id %}">Edit</a>
                                </li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
        </div>
      </div>
    </div>

    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
  
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });

  var d = new Date();
    var year = d.getFullYear();
    document.getElementById("copy-year").innerHTML = year;
</script>
{% endblock extra_scripts %}

templates/rider/ongoing_order.html
{% extends "rider/rider.html" %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="wrapper">
  <div class="page-wrapper">
    <div class="content-wrapper">
      <div class="content">
	      <div class="row">
					<div class="col-12">
						<div class="card card-default">
							<div class="card-header card-header-border-bottom d-flex justify-content-between">
								<h2>On Going Orders</h2>
							</div>

							<div class="card-body">
                <div class="hoverable-data-table">
									<table id="hoverable-data-table" class="table table-hover nowrap" style="width:100%">
										<thead>
											<tr>
                        <th>Customer</th>
                        <th>Sugo</th>
                        <th>Shipping Address</th>
                        <th>Charges</th>
                        <th>Total charge</th>
                        <th>Pay via</th>
                        <th>Date</th>
                        <th style="text-align: right;">Status</th>
											</tr>
										</thead>

                    <tbody>
                      {% for ongoing in ong %}
                        <tr>    
                          <td>{{ongoing.user.customer.first_name}} {{ongoing.user.customer.middle_name}} {{ongoing.user.customer.last_name}} {{ongoing.user.customer.suffix}}<br>
                            {{ongoing.user.customer.contact}}
                          </td>

                          {% if ongoing.other %}
                            <td>{{ongoing.other.note}}</td>
                          {% else %}
                            <td style="display: block;">
                              {% for items in ongoing.items.all %}
                                {{items.quantity}}pc. ({{items.item.title}} {{items.item.price}}) in {{items.partnerstore.store}}<br>
                              {% endfor %}
                            </td>
                          {% endif %}
                                
                          <td>{{ongoing.shipping_address.house_purok_address}} {{ongoing.shipping_address.barangay}}<br>
                            {{ongoing.shipping_address.municipality}} {{ongoing.shipping_address.province}}<br>
                          </td>   
                          <td>Service charge: {{ongoing.service_charge}}<br>
                            Other: {{ongoing.surcharge}}
                          </td>
                          <td>{{ongoing.total}}</td>
                          <td>{{ongoing.payment.payment_choice}}</td>
                          <td>{{ongoing.date_ordered}}</td>
                          <td class="text-right">
                            <div class="dropdown show d-inline-block widget-dropdown">
                              <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdown-recent-order2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static"></a>
                              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-recent-order2">
                                <li class="dropdown-item">
                                  <a href="{% url 'core:rider_order_status' ongoing.id %}">Edit</a>
                                </li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
        </div>
      </div>
    </div>

    <footer class="footer mt-auto">
      <div class="copyright bg-white">
        <p> &copy; 
          <span id="copy-year">2021</span> Copyright Sulogoon Dashboard    
        </p>
      </div>
    </footer>
  </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<script>
  jQuery(document).ready(function() {
    jQuery('input[name="dateRange"]').daterangepicker({
    autoUpdateInput: false,
    singleDatePicker: true,
    locale: {
      cancelLabel: 'Clear'
    }
  });
  
    jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
      jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
    });
    jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
      jQuery(this).val('');
    });
  });

  jQuery(document).ready(function() {
    jQuery('#hoverable-data-table').DataTable({
      "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
      "pageLength": 20,
      "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
    });
  });

  var d = new Date();
    var year = d.getFullYear();
    document.getElementById("copy-year").innerHTML = year;
</script>
{% endblock extra_scripts %}