core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *

app_name = 'core'
 
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('store/<slug>/', PartnerDetailView.as_view(), name='store'),
    path('contact_us/', Contact_Us, name='contact_us'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('partner_dashboard/', PartnerDashBoard, name='partner_dashboard'),
    path('partner_items/', PartnerItems, name='partner_items'),

    path('shop/', AllCategoryView, name='shop'),
    path('others/', OtherView, name='others'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path('admin_dashboard/', AdminDashBoard, name='admin_dashboard'),
    path('admin_profile/', UserAdminProfile, name='admin_profile'),
    path('pending_order/', PendingOrder, name='admin_pending_order'),
    path('all_categories/', AllCategory, name='all_categories'),
    
    path('items/', AllItems, name='all_items'),
    path('all_order/', AllOrder, name='all_order'),
    path('all_stores/', AllStores, name='all_stores'),
    path('all_admins/', AllAdmins, name='all_admins'),

    path('all_admins/edit/<str:pk>/', EditAdmin, name='edit_admin'),
    path('all_dispatchers/edit/<str:pk>/', EditDispatcher, name='edit_dispatcher'),

    path('all_stores/edit/<str:pk>/', EditPartner, name='edit_store'),
    path('all_customers/edit/<str:pk>/', EditCustomer, name='edit_customer'),
    path('all_dispatchers/', AllDispatchers, name='all_dispatchers'),
    path('all_customers/', AllCustomers, name='all_customers'),
    path('ongoing_order/', OnGoingOrder, name='ongoing_order'),
    path('delivered_order/', DeliveredOrder, name='delivered_order'),
    path('partner/<slug>/', PartnerView.as_view(), name='partner'),
    path('dispatch_dashboard/', DispatchDashBoard, name='dispatch_dashboard'),
    path('customer_dashboard/', CustomerDashBoard, name='customer_dashboard'),

    path('shipping_rate/', ShippingRate, name='shipping_rate'),
 
    path('accounts/upload/', UploadSignUp, name='upload'),
    path('accounts/address/', VerificationSignUp, name='address'),
    path('signup_success/', SuccessSignUp, name='signup_success'),
    path('change_password/', ChangePassword, name='change_password'),
    
    path('dispatch/<str:pk>/', UpdateOrder, name='update_order'),
    path('dispatch_order/<str:pk>/', Dispatch, name='dispatch_order'),
    path('dispatcher_pending_order/', DisPendingOrder, name='dispatcher_pending_order'),
    path('dispatcher_ongoing_order/', DisOnGoingOrder, name='dispatcher_ongoing_order'),
    path('dispatcher_delivered_order/', DisDeliveredOrder, name='dispatcher_delivered_order'),
    path('dispatcher_account_settings/', DispatcherAccountSettings, name='dispatcher_account_settings'),
    path('dispatcher_all_order/', DisAllOrder, name='dispatcher_all_order'),

    path('distance_calculator/', DistanceCalculator, name='distance_calculator'),



    path('partner_profile/', UserPartnerProfile, name='partner_profile'),
    path('partner_pending_order/', PartnerPendingOrder, name='partner_pending_order'),
    path('partner_ongoing_order/', PartnerOnGoingOrder, name='partner_ongoing_order'),
    path('partner_delivered_order/', PartnerDeliveredOrder, name='partner_delivered_order'),

    path('', views.adminsearch, name='adminsearch'),

    ###################################CUSTOMER#########################################
    path('customer_pending_order/', CustPendingOrder, name='customer_pending_order'),
    path('customer/order_history/', CustomerOrderHistory, name='customer_order_history'),
    path('customer/order_information/<str:pk>/', CustomerOrderInfo, name='customer_order_information'),
    path('customer_ongoing_order/', CustOngoingOrder, name='customer_ongoing_order'),
    path('customer_delivered_order/', CustDeliveredOrder, name='customer_delivered_order'),
    path('my_profile/', UserCustomerProfile, name='customer_profile'),
    path('customer/my_account/', MyAccountCustomer, name='customer_my_account'),
    path('customer/edit_information/', EditInfoCustomer, name='customer_edit_information'),
    path('customer/edit_address/', EditAddressCustomer, name='customer_edit_address'),
    ###################################CUSTOMER#########################################

    ###################################RIDER#########################################
    path('all_riders/', AllRiders, name='all_riders'),
    path('all_riders/edit/<str:pk>/', EditRider, name='edit_rider'),
    path('rider_dashboard/', RiderDashBoard, name='rider_dashboard'),
    path('rider_order_status/<str:pk>/', RiderOrderStatus, name='rider_order_status'),
    path('rider_status/', RiderStatus, name='rider_status'),
    path('update_item/<str:pk>', UpdateItem, name='update_item'),
    path('rider_account_settings/', RiderAccountSettings, name='rider_account_settings'),
    path('rider_pending_order/', RidePendingOrder, name='rider_pending_order'),
    path('rider_ongoing_order/', RideOngoingOrder, name='rider_ongoing_order'),
    path('rider_delivered_order/', RideDeliveredOrder, name='rider_delivered_order'),
    
    ###################################RIDER#########################################

    ###################################PARTNERSTORE#########################################

    path('partner_all_order/', PartnerAllOrder, name='partner_all_order'),
    

    ###################################PARTNERSTORE#########################################
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
                
        {% include "nav.html"%}
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
          crossorigin=""></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
          
          <link rel="stylesheet" href="{% static 'assets/plugins/leaflet-routing-machine.css' %}">
        <script src="{% static 'assets/plugins/leaflet-measure.js' %}"></script>
        <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'assets/plugins/slimscrollbar/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'assets/plugins/jekyll-search.min.js' %}"></script>
        <script src="{% static 'assets/plugins/charts/Chart.min.js' %}"></script>
        <script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
        <script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-world-mill.js' %}"></script>
        <script src="{% static 'assets/plugins/daterangepicker/moment.min.js' %}"></script>
        <script src="{% static 'assets/plugins/daterangepicker/daterangepicker.js' %}"></script>
        <script src="{% static 'assets/plugins/data-tables/jquery.datatables.min.js' %}"></script>
        <script src="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'assets/js/sleek.bundle.js' %}"></script>
        
        <script src="{% static 'assets/plugins/leaflet-routing-machine.js' %}"></script>
        
    
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}
        
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      
      </div>
    </div>
    <head>
      <!-- jquery -->
      <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>

    <!-- cropper -->

    </head>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

   
  </body>
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="en" class="ie8"><![endif]-->
<!--[if IE 9 ]><html dir="ltr" lang="en" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
{% include "header1.html" %}

<title>{% block head_title %}{% endblock %}</title>
{% block extra_head %} {% endblock %}

<body>
  {% include "nav1.html"%}
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin="" />

  <link href="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/plugins/data-tables/jquery.datatables.min.css' %}" rel="stylesheet" />

  <script src="{% static 'assets/plugins/data-tables/jquery.datatables.min.js' %}"></script>
  <script src="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.js' %}"></script>
  <div class="mt-2">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>

    </div>
  </div>

  {% endfor %}
  {% endif %}

  {% block content %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %}

  {% block extra_scripts %}
  {% endblock extra_scripts %}

  <footer>
    {% include "footer1.html" %}
  </footer>
</body>

</html>

templates/footer.html
{% load static %}
<!-- ------------------------------footer sub end---------------------------------- -->
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Abel|Lato|Open+Sans&display=swap" rel="stylesheet">
<style>
  
    /* footer */
#footer-main{
	background: #000;
	color: white;
	font-size: 0.8rem;
	padding: 2.5rem 0;
    font-family: 'Lato', sans-serif;
}

#footer-main a{
	font-size: 14px;
	display: block;
	margin: 0.3rem;
	color: grey;
}

#footer-main a:hover{
	font-weight: bold;
	color: white;
}

#footer-main h6 a{
    color: white;

    
}



#footer-main hr {
    margin-top: 1rem;
    margin-bottom: 1rem;
    border: 0;
    border-top: 1px solid white;
}

#footer-main img{
	margin-right: 0.6rem;
}
</style>

<footer id="footer-main">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
            <br>

            <h6 class="mt-3"><a href="">FIND A STORE</a></h6>
            <h6 class="mt-3"><a href="">SIGN UP FOR EMAIL</a></h6>
            <h6 class="mt-3"><a href="">BECOME A MEMBER</h6>
            
            <h6 class="mt-3"><a href="/admin/">ADMIN LOGIN</a></h6>
           
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">GET HELP</a></h6>
            <a href="">Order Status</a>
            <a href="">Shipping and Delivery</a>
            <a href="">Returns</a>
            <a href="">Payment Options</a>
            
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">ABOUT US</a></h6>
            <a href="">Products</a>
            <a href="">Company</a>
            <a href="">Partners</a>
            <a href="">News</a>
            <a href="">Contact Us</a>
            
            



        </div>
        <div>
          <br><br>
          <a href="">Business Inquiry</a>
          <br>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          
        </div>
        <div class="col-sm-6">
          
        </div>
        <hr>
        <a href="" style="margin-left: 1rem">Privacy Policy | @sulogoon 2020</a>
      </div>
    </div>
  </footer>
<!-- ------------------------------footer end---------------------------------- -->

templates/footer1.html
{% load static %}

<body>
    <footer>
        <div class="footer_bottom clearfix">
            <div class="container">
                <div class="footer-bottom-inner">
                    <div class="position-footer-bottom">
                        <div class="about-logo"> <a href="#"><img src="{% static 'image/sulogoon/logo.png' %}"
                                    alt="Logo"></a></div>
                    </div>
                    <p class="copyright">Powered By <a href="http://www.yanicabas.com/">Yanicabs</a> Sulogoon &copy;
                        2021</p>
                </div>
            </div>
        </div>
    </footer>
    <a href="#" class="scrollToTop back-to-top" data-toggle="tooltip" title="Top"></a>
</body>

templates/nav1.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}
{% load has_group_tags %}

<nav id="top">
	<div class="container">
		<div class="top-main">
			<div class="top-left">
				<div class="open_time hidden-xs">
					<i class="fa fa-clock-o"></i>
					<span class="open-time">Opening Hours:</span>
					<span>8:00 AM - 8:00 PM</span>
				</div>
			</div>
			<div class="top-right">
				<!-- start account -->
				<div id="header_ac" class="dropdown">
					<a href="indexe223.html?route=account/account" title="My Account" class="dropdown-toggle"
						data-toggle="dropdown">
						<i class="fa fa-user-o hidden-xs"></i> My Account <i class="fa fa-angle-down"></i>
					</a>
					{% if request.user.customer.is_active %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li>
							<button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.customer.profile_pic %}
								<img src="{{request.user.customer.profile_pic.url}}" width="15px;" class="user-image"
									alt="User Image" />
								{% endif %}
								<span class="d-none d-lg-inline-block">{{request.user.customer.first_name}}
									{{request.user.customer.last_name}}</span>
							</button>
						</li>
						<li>
							<a href="/customer/my_account/">
								<i class="mdi mdi-account"></i> My Account
							</a>
						</li>
						<li>
							<a href="/my_profile/">
								<i class="mdi mdi-account"></i> My Profile
							</a>
						</li>
						<li>
							<a href="{% url 'account_logout' %}"> <i class="mdi mdi-logout"></i> Log Out
							</a>
						</li>
					</ul>
					{% elif request.user|has_group:"rider" %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li>
							<button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.rider.profile_pic %}
								<img src="{{request.user.rider.profile_pic.url}}" width="15px;" class="user-image"
									alt="User Image" />
								{% endif %}
								{% if request.user.rider.first_name %}
								<span class="d-none d-lg-inline-block">{{request.user.rider.first_name}}
									{{request.user.rider.last_name}}</span>
								{% endif %}
							</button>
						<li>
							<a href="/rider_account_settings/">
								<i class="mdi mdi-account"></i> My Profile
							</a>
						</li>

						<li class="right-sidebar-in">
							<a href="javascript:0"> <i class="mdi mdi-settings"></i> Setting </a>
						</li>
						<li class="dropdown-footer">
							<a href="/accounts/logout"> <i class="mdi mdi-logout"></i> Log Out </a>
						</li>
						</li>
					</ul>
					{% elif request.user|has_group:"admin" %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li>
							<button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.admin.profile_pic %}
								<img src="{{request.user.admin.profile_pic.url}}" width="15px;" class="user-image"
									alt="User Image" />
								{% endif %}
								<span class="d-none d-lg-inline-block">{{request.user.admin.first_name}}
									{{request.user.admin.last_name}}</span>
							</button>
						</li>
						<li>
							<a href="admin_profile/">
								<i class="mdi mdi-account"></i> My Profile
							</a>
						</li>
						<li>
							<a href="admin_dashboard/">
								<i class="mdi mdi-email"></i> Dashboard
							</a>
						</li>
						<li>
							<a href="{% url 'account_logout' %}"> <i class="mdi mdi-logout"></i> Log Out
							</a>
						</li>
					</ul>
					{% elif request.user|has_group:"partner" %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li>
							<button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.partnerstore.profile_pic %}
								<img src="{{request.user.partnerstore.profile_pic.url}}" width="15px;"
									class="user-image" alt="User Image" />
								{% endif %}
								<span class="d-none d-lg-inline-block">{{request.user.partnerstore.first_name}}
									{{request.user.partnerstore.last_name}}</span>
							</button>
						</li>
						<li>
							<a href="/partner_profile/">
								<i class="mdi mdi-account"></i> My Profile
							</a>
						</li>
						<li>
							<a href="/partner_dashboard/">
								<i class="mdi mdi-email"></i> Dashboard
							</a>
						</li>
						<li>
							<a href="{% url 'account_logout' %}"> <i class="mdi mdi-logout"></i> Log Out
							</a>
						</li>
					</ul>
					{% elif request.user|has_group:"dispatcher" %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li>
							<button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.dispatcher.profile_pic %}
								<img src="{{request.user.dispatcher.profile_pic.url}}" width="15px;" class="user-image"
									alt="User Image" />
								{% endif %}
								<span class="d-none d-lg-inline-block">{{request.user.dispatcher.first_name}}
									{{request.user.dispatcher.last_name}}</span>
							</button>
						</li>
						<li>
							<a href="/dispatcher_account_settings/">
								<i class="mdi mdi-account"></i> My Profile
							</a>
						</li>
						<li>
							<a href="/dispatcher_dashboard/">
								<i class="mdi mdi-email"></i> Dashboard
							</a>
						</li>
						<li>
							<a href="{% url 'account_logout' %}"> <i class="mdi mdi-logout"></i> Log Out
							</a>
						</li>
					</ul>
					{% else %}
					<ul class="dropdown-menu dropdown-menu-right account-link-toggle">
						<li><a href="{% url 'account_signup' %}">Register</a></li>
						<li><a href="{% url 'account_login' %}">Login</a></li>
					</ul>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</nav>
<header>
	<div class="container">
		<div class="header-top">
			<div class="contacts hidden-xs">
				<i class="fa fa-phone"></i>
				<div class="contact-text">
					<div>Contact us:</div>
					<a href="/contact_us">0963 486 6919</a>
				</div>
			</div>
			<!-- start logo -->
			<div id="logo">
				<a href="/"><img src="{% static 'image/sulogoon/logo.png' %}" title="Your Store" alt="Logo"
						class="img-responsive" /></a>
			</div>
			<div class="header-right header-links">
				<!-- start cart -->
				<div class="header_cart">
					<div id="cart" class="btn-group btn-block">
						<a href="{% url 'core:order-summary' %}"
							class="btn btn-inverse btn-block btn-lg dropdown-toggle">
							<span id="cart-total"><span>My Cart</span>{{ request.user|cart_item_count }}</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="header-bottom">
		<div class="container">
			<div class="header-bottom-inner">
				<!-- start menu -->
				<nav id="menu" class="navbar navbar_menu">
					<div class="navbar-header">
						<button type="button" class="btn btn-navbar navbar-toggle" id="btnMenuBar"><i
								class="fa fa-bars"></i></button>
					</div>
					<div id="topCategoryList" class="main-menu menu-navbar clearfix" data-more=More>
						<div class="menu-close hidden-lg hidden-md"><span id="category" class="">Menu</span><i
								class="fa fa-close"></i></div>
						<ul class="nav navbar-nav">
							<li class="menulist home"><a id="home" href="/">Home</a></li>
							<li class="menulist home"><a id="home" href="/shop/">Shop</a></li>
							<li class="menulist home"><a id="home" href="#">Pick Up & Deliver</a></li>
						</ul>
					</div>
				</nav>

				<!-- start search -->
				<div class="btn_search">
					<div class="header-search">
						<div id="mahardhiSearch" class="input-group mahardhi-search">
							<div class="category-search">
							</div>
							<input type="text" name="search" value="" placeholder="Search..."
								class="form-control input-lg ui-autocomplete-input" />
							<span class="btn-search input-group-btn">
								<button type="button" class="btn btn-default btn-lg"><i
										class="fa fa-search"></i></button>
							</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

templates/order_summary.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}

<div id="checkout-cart" class="container">
  <ul class="breadcrumb">
    <li><a href="https://opencart.mahardhi.com/MT03/food/index.php?route=common/home">home</a></li>
    <li><a href="https://opencart.mahardhi.com/MT03/food/index.php?route=checkout/cart">Shopping Cart</a></li>
  </ul>
  <div class="row">
    <aside id="column-left" class="col-sm-3 hidden-xs">
      <div class="category-list">
				<div class="box-category">
					<h3 class="toggled relative">Categories</h3>
					<ul class="list-unstyled parent" id="selectMe-desk">
						<li class="has-more-category">
							{% for cat in cat %}
							<a href="#" class="list-group-item main-item">{{cat.title}}<span class="toggled"></span></a>
							<ul class="list-unstyled child-categories group">
								{% for res in res %}
								<li>
									<a href="{{res.get_absolute_url}}" class="list-group-item">{{res.store}}</a>
								</li>
								{% endfor %}
							</ul>
							{% endfor %}
						</li>
						<li class="has-more-category">
							<a href="#" class="list-group-item main-item">Food<span class="toggled"></span></a>
							<ul class="list-unstyled child-categories group">
								{% for a in item_cat %}
								<li>
									<a href="{{a.get_absolute_url}}" class="list-group-item">{{a.title}}</a>
								</li>
								{% endfor %}
							</ul>
						</li>
						<li class="">
							<a href="/others/" class="list-group-item ">Others<span></span></a>
					</ul>
				</div>
			</div>

			<script>
				$(function () {
					$(".parent .fa.fa-plus").remove();
					$(".parent .toggled").append("<i class='fa fa-plus'></i>");
					$('.parent .toggled').click(function (e) {
						e.preventDefault();
						if (!$(this).parent().hasClass('active')) {
							$('+ ul', $('a.list-group-item.main-item')).slideUp();
							$('a.list-group-item.main-item').removeClass('active');
						}
						$(this).parent().toggleClass('active');
						$('+ ul', $(this).parent()).slideToggle('slow');
						return false;
					});
				});
			</script>

    </aside>

    <div id="content" class="col-sm-9 checkout">
      <h1>Shopping Cart
      </h1>
      <form>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <td class="text-center">Image</td>
                <td class="text-left">Product Name</td>
                <td class="text-left">Model</td>
                <td class="text-left">Quantity</td>
                <td class="text-right">Unit Price</td>
                <td class="text-right">Total</td>
              </tr>
            </thead>
            <tbody>
              {% for a in object.items.all %}
              <tr>
                <td class="text-center"> <a href="#"><img src="{{ a.item.image.url }}" alt="Home-Style Baked Pasta"
                      title="{{ a.item.name }}" class="img-thumbnail" /></a> </td>
                <td class="text-left"><a href="#">{{ a.item.name }}</a> </td>
                <td class="text-left">{{ a.item.slug }}</td>
                <td>
                  <a href="{% url 'core:remove-single-item-from-cart' a.item.slug %}"><i
                      class="fas fa fa-minus mr-3"></i></a>
                  {{ a.quantity }}
                  <a href="{% url 'core:add-to-cart' a.item.slug %}"><i class="fas fa fa-plus ml-3"></i></a>
                </td>
                <td class="text-right">₱{{ a.item.price }}</td>
                <td class="text-right">₱{{ a.get_total_item_price }}</td>
              </tr>
              {% endfor %}
            </tbody>
            {% if object.get_total %}
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td colspan="1"><b>Order Total : </b></td>
              <td><b>₱{{ object.get_total }}</b></td>
            </tr>
            <tr>
              <td colspan="6">
                <a href="/shop/" class="btn btn-primary float-left">Continue Shopping</a>
                <a href="/checkout" class="btn btn-warning float-right ml-2" style="float: right;">Checkout</a>
              </td>
            </tr>
            {% endif %}
          </table>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_scripts %}
<script>
</script>
{% endblock extra_scripts %}